# Generated by Django 3.0.4 on 2020-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.TextField(default='goal', max_length=1000),
        ),
    ]
