# Generated by Django 3.0.4 on 2020-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_habit_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
