# Generated by Django 3.0.4 on 2020-03-07 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200306_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='activity_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together={('habit_tracked', 'activity_date')},
        ),
    ]
