# Generated by Django 3.0.4 on 2020-03-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_habit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal_units',
            field=models.TextField(default='units', max_length=40),
        ),
        migrations.AlterField(
            model_name='habit',
            name='daily_goal',
            field=models.IntegerField(default='How Many Per Day?', max_length=7),
        ),
    ]
