# Generated by Django 3.0.4 on 2020-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200307_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_units',
            field=models.TextField(default='units', max_length=20),
        ),
    ]
