# Generated by Django 3.0.4 on 2020-03-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200307_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='daily_goal',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal_units',
            field=models.TextField(default='', max_length=20),
        ),
    ]
