# Generated by Django 3.0.4 on 2020-03-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200307_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_units',
            field=models.CharField(default='', max_length=20),
        ),
    ]
