# Generated by Django 3.0.4 on 2020-03-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200307_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
    ]
