# Generated by Django 3.0.4 on 2020-03-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_habit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='slug',
            field=models.SlugField(default='', max_length=60, unique=True),
        ),
    ]
