# Generated by Django 3.0.4 on 2020-03-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200307_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='daily_goal',
            new_name='goal',
        ),
        migrations.AddField(
            model_name='habit',
            name='timeframe',
            field=models.CharField(default='', max_length=20),
        ),
    ]
