# Generated by Django 3.0.4 on 2020-03-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200307_2155'),
        ('polls', '0004_auto_20200307_2104'),
    ]

    operations = [
    ]
