# Generated by Django 3.0.4 on 2020-03-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_merge_20200307_2215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='activity_date',
        ),
    ]
