# Generated by Django 3.0.4 on 2020-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_habit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='input_units',
            field=models.IntegerField(default=0,)
        ),
    ]
