# Generated by Django 3.0.4 on 2020-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_tracker_input_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='input_units',
            field=models.IntegerField(default=''),
        ),
    ]
