# Generated by Django 3.0.4 on 2020-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_tracker_input_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='habit',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='goal_units',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracker',
            name='input_units',
            field=models.IntegerField(),
        ),
    ]
