# Generated by Django 3.0.4 on 2020-03-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200308_1656'),
        ('polls', '0016_auto_20200308_1631'),
    ]

    operations = [
    ]
