# Generated by Django 3.0.4 on 2020-03-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200308_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='polls.User'),
        ),
    ]
