# Generated by Django 3.0.4 on 2020-03-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_merge_20200308_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='habit_tracked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit', to='polls.Habit'),
        ),
    ]
